### ISSUE TITLE
func settings ends with System.NullReferenceException

### ISSUE THREAD

**Issue by joescars** [Azure/azure-functions-cli#113]
`func settings` lists out all the related settings commands and then ends with

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Functions.Cli.Actions.HelpAction.DisplayOptions(IEnumerable`1 options)
   at Azure.Functions.Cli.Actions.HelpAction.DisplaySwitches(ActionType actionType)
```

Functionality still works but the error is displayed in red.

**Comment by ahmelsayed** [comment]
closed with @joescars's PR https://github.com/Azure/azure-functions-cli/pull/120
