### ISSUE TITLE
[CLI] func fetch secrets fails for bot service

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-functions-cli#14]
I've created a bot service in Azure. With the latest version of the CLI (0.2.9) I tried fetching the secrets (previously appsettings) using `func fetch secrets <botinstance>`. This fails (see below). I think this is specifically related to the bot service instance; when I try the exact same for a 'normal' function app, it does seem to work. 

``System.NullReferenceException: Object reference not set to an instance of an object.
   at ARMClient.Library.ArmUriTemplate.Bind(Object obj)
   at WebJobs.Script.Cli.Arm.ArmManager.<LoadSiteObjectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<LoadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<GetFunctionAppAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Verbs.FetchVerb.<RunAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NCli.ConsoleApp.<RunAsync>d__5`1.MoveNext()``

**Comment by ahmelsayed** [comment]
note that `0.2.9` is actually quite old. The current release is `1.0.0.beta.9`, we also moved from `azurefunctions` to `azure-functions-cli`.
to work around this error on beta.9, run `func azure login` before you run that command.

**Comment by jsiegmund** [comment]
That is very strange, because I thought it was the other way around (fetch-app-settings is what I was actually used to). I don't know how I got to 0.2.9 then, updated the package again and now I have the right one. What's the best way to keep track of new cli releases?

**Comment by ahmelsayed** [comment]
I'd say releases on this new github repo, but @lindydonna will have the right answer

**Comment by lindydonna** [comment]
@jsiegmund Yes, we will do releases on this repo. (We only just moved to this repo a few days ago, so we didn't have a good place to put the notes.)

**Comment by jsiegmund** [comment]
Great, starred and following the repo :)
