### ISSUE TITLE
Crash while trying to create a functionapp

### ISSUE THREAD

**Issue by cyplo** [Azure/azure-functions-cli#27]
I'm trying to get a full deployment from the CI working - have it just take subscription ID and certificate as parameters and create everything from scratch there to use the functions.

I got stuck on creating the functionapp. Resource group and plan mentioned are newly created from the UI, but I would like to create them from scratch eventually as well.

```
$ func azure functionapp create --name="echo" --subscription="41a9e5b4-0404-4193-9334-6a9d016e7631" --resource-group="uksouthfunctionresources" --location="uksouth" --plan="ukfuncplan"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WebJobs.Script.Cli.Arm.ArmManager.<ArmHttpAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<CreateFunctionAppAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Actions.AzureActions.CreateFunctionAppAction.<RunAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.ConsoleApp.<RunAsync>d__4`1.MoveNext()
```

**Comment by ahmelsayed** [comment]
The plan is to move all management operations to [Azure Cli](https://github.com/Azure/azure-cli) and keep this for dev scenarios. Therefore, I removed create action completely from here.

**Comment by SteveALee** [comment]
Ah, I wondered about the obvious overlap with azure cli. That's a good separation as should be easy to figure which does what.
