### ISSUE TITLE
Update to WebJobs SDK release with improved error message for null connection string

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#3]
_From @lindydonna on December 21, 2016 21:15_

_Copied from original issue: Azure/azure-webjobs-sdk-script#1069_

**Comment by ahmelsayed** [comment]
_From @lindydonna on December 22, 2016 0:36_

@ahmelsayed No, but on email Mathew said he uploaded it manually.

**Comment by ahmelsayed** [comment]
_From @soninaren on December 22, 2016 0:38_

I decompiled the dll to check if my changes are there. Looks like they are present in the binary file. @ahmelsayed can you give me the repro steps?

**Comment by ahmelsayed** [comment]
I don't know how to give you a repro. I updated the refrenced package in `rename-cli` branch. 
Pull, build then run func.exe for a local function app folder that has a timer function for example and no storage account set. You'll get a nullref in `ScriptHostManager.cs:L161`
here is the stack
```
   at Microsoft.Azure.WebJobs.Host.Storage.StorageAccountExtensions.AssertTypeOneOf(IStorageAccount account, StorageAccountType[] types)
   at Microsoft.Azure.WebJobs.Host.SingletonManager.GetLockDirectory(String accountName)
   at Microsoft.Azure.WebJobs.Host.SingletonManager.<TryLockAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.<StartAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) in D:\\repos\\azure-webjobs-sdk-script2\\src\\WebJobs.Script\\Host\\ScriptHostManager.cs:line 123"
```

**Comment by ahmelsayed** [comment]
_From @lindydonna on January 4, 2017 1:16_

Moving to 0.10 milestone

**Comment by soninaren** [comment]
i verified the code fix for triggers and bindings related to storage account and httpTrigger. TimerTrigger needs a seperate fix since it is skipping the current fix code path.

**Comment by soninaren** [comment]
Fixed in the PR's below
https://github.com/Azure/azure-webjobs-sdk/pull/961
https://github.com/Azure/azure-functions-cli/pull/18
