### ISSUE TITLE
System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by amragaey** [Azure/azure-functions-cli#52]
I installed azure-functions-cli package, and I'm trying to create a new function but getting an exception instead. 
This exception occurs in Git Bash, but it's working fine with PowerShell.

> $ func function create

```
Select a language: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_CursorLeft()
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.DisplaySelecionWizard[T](IEnumerable`1 options)
   at WebJobs.Script.Cli.Actions.LocalActions.CreateFunctionAction.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.ConsoleApp.<RunAsync>d__4`1.MoveNext()```

**Comment by ahmelsayed** [comment]
So, this would happen if you happen to run while stdout\stdin are redirected, i.e: there is no actual console handle to manipulate the console with, so interactive stuff won't work. 
the work around is to specify `--language <language> --template <templateName> --name <functionName>` though obviously since there is no way of listing templates now, this is kind of hard to discover unless you know what you're looking for. I'll create another issue to add commands to list available templates.

**Comment by ahmelsayed** [comment]
btw, I was unable to repro using git bash, but I might be using a different console emulator
